var meses = ["ENERO","FEBRERO","MARZO","ABRIL","MAYO","JUNIO","JULIO","AGOSTO","OCTUBRE","NOVIEMBRE","DICIEMBRE"];
alert (meses[0]);
alert (meses[1]);
alert (meses[2]);
alert (meses[3]);
alert (meses[4]);
alert (meses[5]);
alert (meses[6]);
alert (meses[7]);
alert (meses[8]);
alert (meses[9]);
alert (meses[6]);
alert (meses[7]);
alert (meses[8]);
alert (meses[9]);
